name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Build Docker image
        run: docker build -t playwright-tests .
      - name: Run Playwright tests on Docker
        run: |
          docker run \
          --rm \
          --ipc=host \
          -e CI=$CI \
          -e DISABLE_ESLINT_PLUGIN=true \
          -e REACT_APP_BASE_URL=${{ vars.REACT_APP_BASE_URL }} \
          -e REACT_APP_API_URL=${{ vars.REACT_APP_API_URL }} \
          -e REACT_APP_CLIENT_ID=${{ secrets.REACT_APP_CLIENT_ID }} \
          -e SIGNIN_VIA_KAKAO_USERNAME=${{ secrets.SIGNIN_VIA_KAKAO_USERNAME }} \
          -e SIGNIN_VIA_KAKAO_PASSWORD=${{ secrets.SIGNIN_VIA_KAKAO_PASSWORD }} \
          playwright-tests

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
